# Generated by Django 5.0.6 on 2024-06-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
