# Generated by Django 5.0.6 on 2024-06-19 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0005_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_work', models.DateField()),
                ('shift_started_time', models.TimeField()),
                ('break_started_time', models.TimeField()),
                ('break_finished_time', models.TimeField()),
                ('shift_finished_time', models.TimeField()),
                ('client_rep_name', models.CharField(max_length=100)),
                ('client_rep_position', models.CharField(max_length=100)),
                ('staff_signature_image', models.ImageField(blank=True, null=True, upload_to='staff_signatures/')),
                ('client_rep_signature_image', models.ImageField(blank=True, null=True, upload_to='client_rep_signatures/')),
                ('care_home_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
