# Generated by Django 5.0.6 on 2024-06-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='break_finished_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='break_started_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='shift_finished_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='shift_started_time',
            field=models.DateTimeField(),
        ),
    ]
