# Generated by Django 5.0.6 on 2024-06-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_timesheet_break_finished_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='break_finished_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='break_started_time',
            field=models.TimeField(),
        ),
    ]
