# Generated by Django 5.0.6 on 2024-06-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_weekdaterange'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdaterange',
            name='week_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
