# Generated by Django 5.0.6 on 2024-07-01 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_weekdaterange_week_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='care_home_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='staff_name',
            field=models.CharField(default=7, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='care_home_name',
            field=models.CharField(max_length=100),
        ),
    ]
