# Generated by Django 5.0.6 on 2024-07-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_timesheet_care_home_id_timesheet_staff_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('week_name', models.CharField(max_length=100)),
                ('week_day', models.CharField(max_length=100)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_availability_1', models.BooleanField()),
                ('staff_availability_2', models.BooleanField()),
            ],
        ),
    ]
