# Generated by Django 5.0.6 on 2024-07-24 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_week_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('ni_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_date', models.DateField()),
                ('passport_expiry_date', models.DateField()),
                ('brp_number', models.CharField(max_length=50)),
                ('brp_date', models.DateField()),
                ('brp_expiry_date', models.DateField()),
                ('training_number', models.CharField(max_length=50)),
                ('training_date', models.DateField()),
                ('training_expiry_date', models.DateField()),
                ('dbs_number', models.CharField(max_length=50)),
                ('dbs_date', models.DateField()),
                ('dbs_expiry_date', models.DateField()),
                ('personal_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staff.personaldetails')),
            ],
        ),
    ]
