# Generated by Django 5.0.6 on 2024-07-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_personaldetails_documentscollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
