# Generated by Django 5.0.6 on 2024-07-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('week_name', models.CharField(max_length=100)),
                ('week_day', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('staff_required', models.IntegerField()),
            ],
        ),
    ]
