# Generated by Django 5.0.6 on 2024-07-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('staff', '0011_timesheet_care_home_id_timesheet_staff_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weekday', models.CharField(max_length=20)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.weekdaterange')),
            ],
        ),
    ]
