# Generated by Django 5.0.6 on 2024-07-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_dateinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
