# Generated by Django 5.0.6 on 2024-07-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_week_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='date',
        ),
    ]
