# Generated by Django 5.0.6 on 2024-07-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_week_end_time_remove_week_staff_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='week_number',
        ),
        migrations.RemoveField(
            model_name='week',
            name='year',
        ),
    ]
