# Generated by Django 5.0.6 on 2024-07-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_remove_week_week_number_remove_week_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='care_home_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
