# Generated by Django 5.0.6 on 2024-07-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_week_care_home_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='staff_required_1',
        ),
        migrations.RemoveField(
            model_name='week',
            name='staff_required_2',
        ),
        migrations.RemoveField(
            model_name='week',
            name='staff_required_3',
        ),
        migrations.RemoveField(
            model_name='week',
            name='staff_required_4',
        ),
    ]
