# Generated by Django 5.0.6 on 2024-07-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_remove_week_staff_required_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='staff_required_1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='staff_required_2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='staff_required_3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='staff_required_4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
