# Generated by Django 5.0.6 on 2024-06-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
