# Generated by Django 5.0.6 on 2024-06-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
