# Generated by Django 5.0.6 on 2024-06-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
