# Generated by Django 5.0.6 on 2024-07-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_home_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('week_name', models.CharField(max_length=100)),
                ('staff_required_field', models.CharField(max_length=50)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_required_sum', models.IntegerField(default=0)),
            ],
        ),
    ]
